# Configuration for the did-helper, should only be used for demonstrational
# deployments, see https://github.com/wistefan/did-helper
did:
  enabled: ${services_enabled.did}
  # fullnameOverride: ${did_host_name} NOT AVAILABLE, default name: did-helper
  secret: ${iss_secret}
  serviceType: ClusterIP
  port: ${did_config.port}
  #! INGRESS: only open for clean up in the tests.
  ingress:
    enabled: ${ingress_enabled.did}
    host: ${did_domain}
    # no TLS option available.
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
  cert:
    country: ${did_config.country}
    state: ${did_config.state}
    locality: ${did_config.locality}
    organization: ${did_config.organization}
    commonName: ${did_config.common_name}
