# https://github.com/FIWARE-Ops/data-space-connector/blob/data-space-connector-3.0.1/charts/trust-anchor/values.yaml

# Generate passwords for the mysql database automatically
generatePasswords:
  enabled: ${services_enabled.generate_passwords}
  secretName: ${mysql_config.secret}

# Database for the trust anchor
mysql:
  enabled: ${services_enabled.mysql}
  fullnameOverride: ${mysql_host_name}
  auth:
    existingSecret: ${mysql_config.secret}
  primary:
    persistence:
      enabled: false
  secondary:
    persistence:
      enabled: false
  initdbScripts:
    create.sql: |
      CREATE DATABASE ${mysql_config.db_name_tir};
