# https://github.com/FIWARE-Ops/data-space-connector/blob/data-space-connector-3.0.1/charts/trust-anchor/values.yaml

trusted-issuers-list:
  enabled: ${services_enabled.til}
  fullnameOverride: ${til_host_name}
  ingress:
    til:
      enabled: ${ingress_enabled.til}
      annotations:
        kubernetes.io/ingress.class: ${ingress_class}
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: ${til_domain}
          paths:
            - path: /
              pathType: Prefix
      # tls:
      #   - secretName: ${til_secret_tls}
      #     hosts:
      #       - ${til_domain}
    tir:
      enabled: ${ingress_enabled.tir}
      annotations:
        kubernetes.io/ingress.class: ${ingress_class}
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: ${tir_domain}
          paths:
            - /
      # tls:
      #   - secretName: ${tir_secret_tls}
      #     hosts:
      #       - ${tir_domain}
  database:
    persistence: true
    host: ${mysql_host_name}
    username: ${mysql_config.username_root}
    name: ${mysql_config.db_name_tir}
    existingSecret:
      enabled: true
      name: ${mysql_config.secret}
      key: ${mysql_config.secret_key}
