resource "helm_release" "ds_connector" {
  version          = var.connector.version
  chart            = var.connector.chart_name
  repository       = var.connector.repository
  name             = var.services_names.connector
  namespace        = var.namespace
  create_namespace = true
  wait             = true
  timeout          = 2400 # 40 minutes

  values = [
    templatefile("${local.helm_conf_yaml_path}/connector.yaml", {
      ingress_class       = "traefik",
      til_operator_domain = "trusted-issuers-list.ds-operator.svc.cluster.local",
      ##########################################################################
      ## VERIFIERS/CREDENTIAS CONFIGURATION SERVICE                           ##
      ##########################################################################
      # Generate a password for the database connection of trust-anchor.
      generate_passwords_enabled = true,
      iss_secret                 = "issuance-secret",
      # MySQL configuration
      #   Secrets generated by: authentication
      mysql_enabled    = true,
      mysql_host_name  = var.services_names.mysql,
      mysql_secret     = "mysql-database-secret",
      mysql_tildb_name = "tildb",
      mysql_ccsdb_name = "ccsdb",
      mysql_root_pass  = "root",
      mysql_secret_key = "mysql-root-password",
      # Credentials Configuration Service
      ccs_enabled        = true,
      ccs_host_name      = var.services_names.ccs,
      ccs_db_persistence = true,
      # Trusted Issuers List
      til_enabled         = true,
      til_host_name       = var.services_names.til,
      til_ingress_enabled = true,
      til_domain          = local.dns_dir[local.dns_domains.til],
      til_secret_tls      = local.secrets_tls[local.dns_domains.til],
      til_db_persistence  = true,
      # DID service
      did_enabled         = true,
      did_host_name       = var.services_names.did,
      did_port            = 3002,
      did_ingress_enabled = true,
      did_domain          = local.dns_dir[local.dns_domains.did],
      did_secret_tls      = local.secrets_tls[local.dns_domains.did],
      # VCVerifier
      vcv_enabled         = true,
      vcv_host_name       = var.services_names.vcv,
      vcv_ingress_enabled = true,
      vcv_domain          = local.dns_dir[local.dns_domains.vcv],
      vcv_secret_tls      = local.secrets_tls[local.dns_domains.vcv],
      ##########################################################################
      ## PROXY                                                                ##
      ##########################################################################
      # PostgreSQL configuration
      postgresql_enabled               = true,
      postgresql_host_name             = var.services_names.postgresql,
      postgresql_papdb_name            = "pap",
      postgresql_secret                = "postgresql-database-secret",
      postgresql_secrect_key_adminpass = "postgres-admin-password", # not editable
      postgresql_secrect_key_userpass  = "postgres-user-password",  # not editable
      # Odrl-pap
      odrl_pap_enabled         = true,
      odrl_pap_host_name       = var.services_names.pap,
      odrl_pap_ingress_enabled = true,
      odrl_pap_domain          = local.dns_dir[local.dns_domains.pap],
      odrl_pap_secret_tls      = local.secrets_tls[local.dns_domains.pap],
      # Opa
      opa_enabled = true,
      opa_port    = 8181,
      # APISIX
      apisix_enabled = true,
      # apisix_host_name = var.services_names.apisix,
      apisix_ingress_enabled = true,
      apisix_domain          = "apisix.provider-a.local",
      ##########################################################################
      ## BROKER                                                               ##
      ##########################################################################
      # Postgis
      postgis_enabled               = true,
      postgis_host_name             = var.services_names.postgis,
      postgis_secret                = "postgis-database-secret",
      postgis_secrect_key_adminpass = "postgres-admin-password", # not editable
      postgis_secrect_key_userpass  = "postgres-user-password",  # not editable
      postgis_db_username           = "postgres",
      # Scorpio
      scorpio_enabled         = true,
      scorpio_host_name       = var.services_names.scorpio,
      scorpio_ingress_enabled = true,
      scorpio_domain          = local.dns_dir[local.dns_domains.scorpio],
      scorpio_secret_tls      = local.secrets_tls[local.dns_domains.scorpio],
    })
  ]
}
