# Configuration for the credentials-config-service to be deployed as part of the
# connector, see https://github.com/FIWARE/helm-charts/tree/main/charts/credentials-config-service
# for all options.
#! INGRESS: only open for clean up in the tests.
credentials-config-service:
  enabled: ${services_enabled.ccs}
  fullnameOverride: ${ccs_host_name}
  service:
    type: ClusterIP
    port: ${ccs_config.port}
  ingress:
    enabled: ${ingress_enabled.ccs}
    annotations:
      kubernetes.io/ingress.class: ${ingress_class}
      # forcing everything to use ssl
      ingress.kubernetes.io/ssl-redirect: "true"
      # example annotations, allowing cert-manager to automatically create tls-certs
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ${ccs_domain}
        paths:
          - /
    # tls:
    #   - secretName: ${ccs_secret_tls}
    #     hosts:
    #       - ${ccs_domain}
  database:
    persistence: true
    host: ${mysql_host_name}
    username: ${mysql_config.username_root}
    name: ${mysql_config.db_name_ccs}
    existingSecret:
      enabled: ${services_enabled.generate_passwords}
      name: ${mysql_config.secret}
      key: ${mysql_config.secret_key}
