# Configuration for the trusted-issuers-list to be deployed as part of the
# connector, see https://github.com/FIWARE/helm-charts/tree/main/charts/trusted-issuers-list
# for all options.
#! INGRESS: only open for clean up in the tests.
trusted-issuers-list:
  enabled: ${services_enabled.til}
  fullnameOverride: ${til_host_name}
  service:
    type: ClusterIP
    port: ${til_config.port}
  ingress:
    til:
      enabled: ${ingress_enabled.til}
      annotations:
        kubernetes.io/ingress.class: ${ingress_class}
        # forcing everything to use ssl
        ingress.kubernetes.io/ssl-redirect: "true"
        # example annotations, allowing cert-manager to automatically create tls-certs
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: ${til_domain}
          paths:
            - /
      # tls:
      #   - secretName: ${til_secret_tls}
      #     hosts:
      #       - ${til_domain}
  database:
    persistence: true
    host: ${mysql_host_name}
    username: ${mysql_config.username_root}
    name: ${mysql_config.db_name_til}
    existingSecret:
      enabled: ${services_enabled.generate_passwords}
      name: ${mysql_config.secret}
      key: ${mysql_config.secret_key}
