# A PostgreSQL instance managed by CloudNativePG (modules/postgres/operator), deployed
# with the cloudnative-pg "cluster" chart. Services do not get their own instance: each
# one requests a database and a user in it with the modules/postgres/database submodule.

locals {
  superuser_secret_name = "${var.name}-superuser"
  host                  = "${var.name}-rw.${var.namespace}.svc.cluster.local"

  cluster_values = {
    type             = var.type
    mode             = "standalone"
    fullnameOverride = var.name

    version = {
      postgresql = var.postgresql_version
      postgis    = var.postgis_version
    }

    cluster = {
      instances = var.instances
      # A PodDisruptionBudget on a single instance would block node drains
      enablePDB = var.instances > 1

      # The superuser password comes from Vault instead of being generated by the operator
      enableSuperuserAccess = true
      superuserSecret       = local.superuser_secret_name

      storage = {
        size         = var.storage_size
        storageClass = var.storage_class != null ? var.storage_class : "" # "" = cluster default
      }

      monitoring = {
        enabled = false
      }
    }

    backups = {
      enabled = false
    }
  }
}

# Superuser credentials, generated in Vault and only synced into this namespace
module "superuser_credentials" {
  source = "../vault/consumer"

  name            = "pg-${var.name}-superuser"
  namespace       = var.namespace
  vault_namespace = var.vault_namespace
  vault_address   = var.vault_address

  secrets = {
    (local.superuser_secret_name) = {
      vault_path       = "postgres/${var.name}/superuser"
      static           = { username = "postgres" }
      generated_fields = ["password"]
      type             = "kubernetes.io/basic-auth"
    }
  }
}

resource "helm_release" "cluster" {
  name      = var.name
  namespace = var.namespace

  repository = "https://cloudnative-pg.github.io/charts"
  chart      = "cluster"
  version    = var.chart_version

  values = [yamlencode(local.cluster_values)]

  # The superuser Secret must exist before the operator bootstraps the instance
  depends_on = [module.superuser_credentials]
}

# Helm does not wait for the pods the operator creates, so this Job waits until the
# instance accepts connections: applying the module means a usable instance.
resource "kubernetes_job_v1" "wait_ready" {
  metadata {
    name      = "${var.name}-wait-ready"
    namespace = var.namespace
  }

  wait_for_completion = true

  timeouts {
    create = "10m"
    update = "10m"
  }

  spec {
    backoff_limit = 0

    template {
      metadata {
        labels = { app = "pg-wait-ready", cluster = var.name }
      }

      spec {
        restart_policy = "Never"

        container {
          name    = "wait"
          image   = var.client_image
          command = ["sh", "-c", "until pg_isready -q -h \"$PGHOST\"; do echo \"waiting for $PGHOST\"; sleep 3; done"]

          env {
            name  = "PGHOST"
            value = local.host
          }
        }
      }
    }
  }

  depends_on = [helm_release.cluster]
}
